export const questionlist = [
    {Q: "Which of the following has the highest attack stat?",
        A: "Rayquaza",
        B: "Regigigas",
        C: "Groudon",
        D: "Haxorus",
        Ans: "B"
    },
    {Q: "Which of the following has the highest hp stat?",
        A: "Wailord",
        B: "Snorlax",
        C: "Hariyama",
        D: "Giratina",
        Ans: "A"
    },
    {Q: "What is the defense stat of Cloyster?",
        A: "145",
        B: "155",
        C: "180",
        D: "210",
        Ans: "C"
    },
    {Q: "Which stat is the highest for Tangrowth?",
        A: "HP",
        B: "Attack",
        C: "Defense",
        D: "Special Attack",
        Ans: "C"
    },
    {Q: "Which of the following has the highest speed stat?",
        A: "Greninja",
        B: "Talonflame",
        C: "Weavile",
        D: "Serperior",
        Ans: "C"
    },
    {Q: "What is the speed stat of Aerodactyl?",
        A: "120",
        B: "130",
        C: "135",
        D: "140",
        Ans: "B"
    },
    {Q: "What is the attack stat of Chansey?",
        A: "20",
        B: "15",
        C: "10",
        D: "5",
        Ans: "D"
    },
    {Q: "Which stat is the highest for Exploud?",
        A: "HP",
        B: "Attack",
        C: "Special Attack",
        D: "Speed",
        Ans: "A"
    },
    {Q: "Which of the following has the highest total stat?",
        A: "Slowking",
        B: "Toxicroak",
        C: "Nidoking",
        D: "Scyther",
        Ans: "D"
    },
    {Q: "Which stat is the highest for Heatran?",
        A: "HP",
        B: "Defense",
        C: "Special Attack",
        D: "Special Defense",
        Ans: "C"
    },
]